### ISSUE TITLE
Encoder ends with two LayerNorm layers

### ISSUE THREAD

**Issue by joakimjohnander** [Atten4Vis/ConditionalDETR#11]
Hey,

First and foremost, thank you for your great work. I have one question. The encoder (using default settings) seems to terminate with two `nn.LayerNorm` . One is within `TransformerEncoderLayer` and the other within `TransformerEncoder`. Is this intentional?

Best regards,
Joakim

**Comment by DeppMeng** [comment]
Hi,

It is not intentional. We just use the same code as DETR on this part. We did not study how it affect the performance.
