### ISSUE TITLE
How extract precision, recall and f1-score metrics

### ISSUE THREAD

**Issue by jackonealll** [Atten4Vis/ConditionalDETR#13]
## ❓ How to do something using DETR

Describe what you want to do, including:
1. what inputs you will provide, if any: I would like to know how to extract precision, recall and f1-score metrics.
2. what outputs you are expecting: I only have AP and AR metrics provided by coco evaluater.

I am trying to use the following code but it gives me a numpy matrix:

```
precision = coco_eval.eval['precision']
recall = coco_eval.eval['recall']
```

Can you help me?

**Comment by DeppMeng** [comment]
Hi, we use standard [COCOAPI](https://github.com/cocodataset/cocoapi) for evaluation. If you want to extract certain metrics, you may need to refer to the COCOAPI documents. It is not directly related to our method.
