### ISSUE TITLE
Can you provide the checkpoints of ConditionalDETR-R50 and -R101 trained with 108 epochs ?

### ISSUE THREAD

**Issue by truetone2022** [Atten4Vis/ConditionalDETR#15]
I can't replicate the result of ConditionalDETR-R50 and -R101 trained with 108 epochs
The replicated result of ConditionalDETR-R50 trained with 108 epochs
<img width="893" alt="image" src="https://user-images.githubusercontent.com/45789117/155834070-cf1777d7-0c2d-49ff-9585-63c2412687ad.png">
The replicated result of ConditionalDETR-R101 trained with 108 epochs
<img width="930" alt="image" src="https://user-images.githubusercontent.com/45789117/155834106-0aa1e2b7-018f-4c46-867c-6b173abff69d.png">

**Comment by DeppMeng** [comment]
can you provide your full training configs? e.g., batch-size, number of GPU used? So that we can help you locate the problem.

**Comment by truetone2022** [comment]
The only difference is that i use 32 A100 gpus to train the model .

**Comment by truetone2022** [comment]
if possible, can you provide the checkpoint of these two models trained with 108 epochs? Very thanks!

**Comment by truetone2022** [comment]
if not, can you provide the reproducible training configs of these two models trained with 108 epochs? Very thanks!

**Comment by truetone2022** [comment]
Thanks for your helpful advice! You are so kind!
