### ISSUE TITLE
Hello, may I ask how to visualize the spatial attention diagram in the paper? Where is the corresponding code?

### ISSUE THREAD

**Issue by wulele2** [Atten4Vis/ConditionalDETR#20]

**Comment by wulele2** [comment]
I have successfully visualized, thank you for your great work。

**Comment by SaifeiYan** [comment]
> 
could you send the visualized file to me ,thanks!

**Comment by SaifeiYan** [comment]
> I have successfully visualized, thank you for your great work。

**Comment by wulele2** [comment]
https://github.com/wulele2/Detr-heat-map-visualization

**Comment by SaifeiYan** [comment]
> https://github.com/wulele2/Detr-heat-map-visualization
Hi, I ran the code you posted and got the following error, how do I fix it? Thanks a lot!
Traceback (most recent call last):
  File "test.py", line 117, in <module>
    model.transformer.decoder.layers[-1].multihead_attn.register_forward_hook(
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'TransformerDecoderLayer' object has no attribute 'multihead_attn'

**Comment by wulele2** [comment]
我运行没问题，可能是pytorch版本问题，我的是1.7.1
