### ISSUE TITLE
Add ConditionalDETR to HuggingFace Transformers

### ISSUE THREAD

**Issue by NielsRogge** [Atten4Vis/ConditionalDETR#21]
Hi!

As ConditionalDETR seems like some (relatively) minor modifications to the original DETR, it might make sense to add ConditionalDETR to [HuggingFace Transformers](https://github.com/huggingface/transformers) to increase visibility and adoption. We do have the original DETR in the library, found here: https://huggingface.co/docs/transformers/model_doc/detr. This also comes with nice inference widgets on the hub, check out this one for instance (on the right -> you can directly try out DETR in the browser!): https://huggingface.co/facebook/detr-resnet-50.

The Python implementation is made in a single python script, found here: https://github.com/huggingface/transformers/blob/main/src/transformers/models/detr/modeling_detr.py.

So, if we want to add ConditionalDETR, it would have to be implemented in modeling_conditional_detr.py, which includes the modifications compared to modeling_detr.py.

Are you interested in adding this model to the library?

Kind regards,

Niels, 
ML Engineer @ HuggingFace

**Comment by DeppMeng** [comment]
Hi Niels,

Thank you for your message! That will be great, we are very interested in. I am kind of busy today. I will check out the implementation of DETR in HuggingFace and implement Conditional DETR based on it in the next couple days.

If I understand correctly, we will need to provide both the single-script implementation and the pretrained weights, right?

Thanks,
Depu

**Comment by NielsRogge** [comment]
Yes that's correct! Maybe it might be easiest to set up a slack channel for easier communication. Is that ok for you?

**Comment by DeppMeng** [comment]
Sure. I am not very familiar with Slack. Can you invite me to a slack channel? My email address
is mdpustc@gmail.com
