### ISSUE TITLE
How to add Group DETR in DINO-Deformable-DETR

### ISSUE THREAD

**Issue by xiaoruiai** [Atten4Vis/ConditionalDETR#29]
Hi, Thank you for your wonderful works. If I want to add Group DETR in DINO-Deformable-DETR, how to use Mixed Query Selection that generate box for different groups?

**Comment by charlesCXK** [comment]
Hi, we generate multiple groups of proposals in this step.

**Comment by xiaoruiai** [comment]
Multiple groups of proposals are the same？How to generate different groups of proposals？

**Comment by charlesCXK** [comment]
> Multiple groups of proposals are the same？How to generate different groups of proposals？

Hi, we use different heads to generate different groups of proposals.

**Comment by xiaoruiai** [comment]
I get it. Thank you very much for your patient guide.
