### ISSUE TITLE
The code of validate the model performance (AP，AP50)

### ISSUE THREAD

**Issue by Huzhen757** [Atten4Vis/ConditionalDETR#6]
Excuse me, I didn't see which script is used to calculate the accuracy(AP, AP50,AP75 etc.) on the COCO-2017val dataset.
How can I review the experimental results in the paper? should I write a new script to validate accuracy ?

**Comment by Huzhen757** [comment]
Excuse me, I didn't see which script is used to calculate the accuracy(AP, AP50,AP75 etc.) on the COCO-2017val dataset.
How can I review the experimental results in the paper?   should I write a new  script to validate  accuracy ?

**Comment by DeppMeng** [comment]
Hi, please refer this section of the readme for model evaluation on COCO-val dataset.
https://github.com/Atten4Vis/ConditionalDETR#evaluation
